### PR TITLE
Updates regex bug to be more inclusive of all other characters

### PR DESCRIPTION
**Pull request by cjoshea9**

### CODE REVIEW

**Comment by g-harel** [comment]
I don't really understand this change, it seems like it's now saying "everything that is whitespace + everything that isn't whitespace" instead of just "everything". Do you have an example case that motivated this change?

**Comment by cjoshea9** [comment]
Apparently a normal space is not included in the . for regex's. I used the tool that Michael recommended and figured this out, and this was a suggestion I found on the web that is commonly used in place of the .  @g-harel

**Comment by cjoshea9** [comment]
Had to update the sign font across the site because the old font no longer works

**Comment by g-harel** [comment]
Hmm, seems like `.` doesn't match newlines, but I don't think that would be an issue for this use case. You'd probably want to replace `[.]*` with `.*` to have it behave as expected (brackets make it look for a `.` literal instead of wildcard).

**Comment by cjoshea9** [comment]
Oh that makes sense.

**Pull request merged**
